name: Bug Report
description: Report a bug in DreamerAI
title: "[bug]: "
labels: ["bug", "triage"]
assignees:
  - darwimmusic

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: dropdown
    id: planet
    attributes:
      label: Affected Planet / Module
      options:
        - Mercury (Horoscopo Diario)
        - Venus (Mapa Astral)
        - Mars (Tarot)
        - Jupiter (Sonhos)
        - Saturn (Compatibilidade)
        - Moon (Fases da Lua)
        - Neptune (Meditacao)
        - Solar System / 3D Core
        - Navigation / UI
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect?
      placeholder: Describe the bug clearly...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, screen size
      placeholder: |
        Browser: Chrome 121
        OS: Windows 11
        Screen: 1920x1080
    validations:
      required: false
