name: Feature Request
description: Suggest a new feature or enhancement
title: "[feat]: "
labels: ["enhancement"]
assignees:
  - darwimmusic

body:
  - type: markdown
    attributes:
      value: |
        Have an idea for DreamerAI? Share it here!

  - type: dropdown
    id: planet
    attributes:
      label: Target Planet / Module
      options:
        - Mercury (Horoscopo Diario)
        - Venus (Mapa Astral)
        - Mars (Tarot)
        - Jupiter (Sonhos)
        - Saturn (Compatibilidade)
        - Moon (Fases da Lua)
        - Neptune (Meditacao)
        - Solar System / 3D Core
        - Navigation / UI
        - New Module
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What do you want to add or improve?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature valuable for users?
    validations:
      required: false
